name: 'Publish to Blog'
description: 'Auto-publish developer blogs to medium'
inputs:
  gh_token:
    description: 'Github token'
    required: true
  role_id:
    description: 'Vault Role ID'
    required: true
  secret_id:
    description: 'Vault Secret ID'
    required: true
  endpoint:
    description: 'Vault Endpoint'
    required: true      
outputs:
  medium_url:
    description: 'The Medium URL of the published article'
runs:
  using: 'node16'
  main: 'src/index.js'